= Nutzungsvorgaben Datum & Zeit Persistenz

include::partial$library.adoc[]

Die Bibliothek `isy-datetime-persistence` dient als Ergänzung der Bibliothek `isy-datetime`. Mit ihr können Datums-Objekte des Pakets `isy-datetime` in Datenbanken abgelegt und wieder ausgelesen werden.

== Einbinden in das Projekt

Die Bibliothek `isy-datetime-persistence` wird mit folgendem Code-Abschnitt in die POM-Datei des Projekts eingebunden:

[[einbindung-datetime-persistence]]
[source,xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact</groupId>
    <artifactId>isy-datetime-persistence</artifactId>
    <version>${isy-datetime-persistence.version}</version>
</dependency>
----
Der Wert von `isy-datetime-persistence.version`  wird dabei in den Properties der POM-Datei gesetzt.

Durch diese Dependency werden auch `isy-datetime` und `jakarta.persistence` eingebunden.

Dem Entwickler stehen nun einige Entitäten und ein Converter zur Verfügung, mit den Datums-Objekte verarbeitet werden können.

[[entitaeten]]
== Entitäten

Im Paket `de.bund.bva.isyfact.datetime.persistence` befinden sich die Klassen:

* `UngewissesDatumEntitaet`,
* `UngewisseZeitEntitaet`,
* `ZeitraumEntitaet`.

Diese Klassen bilden die Datenbank-Entitäten zu den entsprechenden Klassen aus `isy-datetime` gemäß dem Standard, der in `jakarta.persistence` definiert ist.

[[attribute-converter]]
== Attribute Converter

Die Klasse `PeriodAttributeConverter` im Unterpaket `attributeconverter` stellt einen `Converter` zur Konvertierung von Objekten der Klasse `Period` aus `java.time` zur Verfügung.
Die Konvertierung erfolgt dabei automatisch.
Das Speichern erfolgt in der ISO-8601-Darstellung als String.
