name: Maven Dependency Scan
on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
    paths:
      - 'pom.xml'
  workflow_dispatch:

jobs:
  SnykScan:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v1.6.0
    with:
      jdk-version: 21
      snyk-reference: $GITHUB_REF_NAME
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
